[monitor:///var/log/syslog]
index = ecotrack
sourcetype = syslog
disabled = false

[monitor:///var/log/auth.log]
index = ecotrack
sourcetype = linux_secure
disabled = false

[monitor:///var/log/mosquitto/mosquitto.log]
index = ecotrack
sourcetype = mosquitto
disabled = false

[monitor:///var/log/snort/alert]
index = ecotrack
sourcetype = snort_alert
disabled = false
