SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off

# SQL Injection
SecRule ARGS "@detectSQLi" \
"id:1001,phase:2,deny,status:403,log,msg:'SQL Injection ECOTRACK'"

# XSS
SecRule ARGS "@detectXSS" \
"id:1002,phase:2,deny,status:403,log,msg:'XSS ECOTRACK'"

# Path Traversal
SecRule REQUEST_URI "@rx \.\./" \
"id:1003,phase:1,deny,status:403,log,msg:'Path Traversal ECOTRACK'"
